### ISSUE TITLE
How do I set the title

### ISSUE THREAD

**Issue by RickCogley** [njleonzhang/docsify-edit-on-github#1]
Hi - thank you for this plugin. Could you please tell me, how do I set the title of the "Edit on github" link? I'm loading like this and it's working:  

```js
...
plugins: [
 EditOnGithubPlugin.create(
   'https://github.com/RickCogley/myrepo/blob/master/docs/'
    ),
...
```

...but I noticed in your readme that I can set the title, but, I'm a newb when it comes to js, so, I thought I would ask, if you don't mind. 

Thanks in advance.

**Comment by njleonzhang** [comment]
@RickCogley the third parameter of function `EditOnGithubPlugin.create` is the title.

```
plugins: [
 EditOnGithubPlugin.create(
   'https://github.com/RickCogley/myrepo/blob/master/docs/',
   undefined,   // pass undefined if you don't care this parameter
   'your title'
    ),
```

**Comment by RickCogley** [comment]
TIL about undefined. It works! Thanks!
