### ISSUE TITLE
Switch CDN from "unpkg.com" to "cdn.jsdelivr.net"

### ISSUE THREAD

**Issue by axel3rd** [njleonzhang/docsify-edit-on-github#12]
In Febrary 2020 ([#1022](https://github.com/docsifyjs/docsify/pull/1022)), docsify has switch [its CDN](https://docsify.js.org/#/cdn) from `unpkg.com` to `cdn.jsdelivr.net`. 

As a main plugin, it would be nice if *docsify-edit-on-github* can be hosted on `cdn.jsdelivr.net` ; more coherent with other docsify plugins.

**Comment by njleonzhang** [comment]
@axel3rd enabled，thx for suggestion.


https://cdn.jsdelivr.net/npm/docsify-edit-on-github
