### ISSUE TITLE
i18n for the edit label

### ISSUE THREAD

**Issue by mateuswetah** [njleonzhang/docsify-edit-on-github#4]
Hi, thank you for the simple and efficient plugin!

I have a question/request. I'm not sure how complicated would it be to implement this, but could it be possible to set the label for different languages of the documentation? For example:

```
EditOnGithubPlugin.create(
    docBase, 
    docEditBase, 
    title: {
        '/': 'Edit on Github',
        '/pt-br': 'Editar no Github'
    }
)
```

**Comment by njleonzhang** [comment]
I will try to support later.

**Comment by njleonzhang** [comment]
supported in eb35065c00a374c266a3c494b30006c20e96c43c, refer to readme
