### ISSUE TITLE
Can't open link on another tab

### ISSUE THREAD

**Issue by mateuswetah** [njleonzhang/docsify-edit-on-github#5]
Hi guys, thanks again for the plugin!

I'm noticing a strange behavior, not sure if directly related to the plugin:
- Open the link directly: Works Fine :) ;
- Open the link by right clicking on browser to open another tab: 404 error on github :(

Test it here: https://tainacan.github.io/tainacan-wiki/#/pt-br/getting-started

Any ideas?

**Comment by njleonzhang** [comment]
the navigate behavior is implemented by `click` event. So only click can trigger the correct jump currently.

https://github.com/njleonzhang/docsify-edit-on-github/blob/390d71a2e8781e8b119c8bc329c8fa5a7d6421ce/index.js#L30-L33

**Comment by mateuswetah** [comment]
I see... wouldn't it be possible to do something like:
```
'<a :href="getDocBase() " target="_blank">',
```
Then
```
function getDocBase(event, vm) {
      var docName = vm.route.file

      if (docName)
         return docEditBase + docName;
      else
         return docBase;
}
```
?

**Comment by njleonzhang** [comment]
Yeah, I think it can be implemented as you wished. I Will consider to implement later. If you need this feature currently, you can implement it and submit a PR. 😄

**Comment by njleonzhang** [comment]
prevent the right click in commit 470917a9be2788b16c4347ea5e3e842f907431ea
