### ISSUE TITLE
Small bug: relative paths don't work (a slash needs to be appended to the URL)

### ISSUE THREAD

**Issue by trusktr** [njleonzhang/docsify-edit-on-github#6]
F.e., if my doc page is

```
http://localhost:3000/#/./install
```

then clicking the "Edit on GitHub" link takes me to https://github.com/infamous/infamous/tree/master/docs./install.md, which is 404 on GitHub (the dot in `docs.`).

Seems like the simple solution is to ensure that there's always a slash between the GitHub URL and the appended path.

**Comment by njleonzhang** [comment]
can not reproduce
