### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by StoneyJackson** [njleonzhang/docsify-edit-on-github#8]
I would love to use this, and even extend it, contribute to it, etc. But I don't see a license on it. Would you be willing to put an open source license on it? [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html)? [MIT](https://en.wikipedia.org/wiki/MIT_License)? etc.?

**Comment by njleonzhang** [comment]
@StoneyJackson done

**Comment by StoneyJackson** [comment]
@njleonzhang Thanks!
